server:
  port: 8080

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  cache:
    type: redis
    redis:
      cache-null-values: true
  redis:
    host: ENC(0me8e7OGnqW3EquGC7MYC82MSRctP65T)
    port: 6379
  datasource:
    url: ENC(SxetzCE1mdqrZAIqgbQb6fLr4Ut0ArP9qe1Imae1DvGsZQfJ5W4QY7MgE58wTgfF4WRPKWQox3J6UYCMo54tTJnVQcdVMGLhOCm5Ckoc/RU=)
    username: ENC(waigO2x+FI07NHMEmyfQ3w==)
    password: ENC(B4pEKuqnz7tW3mgIqDR5Tmj/1W1eeVoA)
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

jwt:
  secret-key: ENC(X0XkZrKEdEMjdPbe/9F3vdWtaeVelnDSlAXCKLzRPw/7l56nwudXk6CFPUXinvY0)
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@gmail.com

max_loan_day: 14
max_loan_quantity: 5
loan_limited: 2

jasypt:
  encryptor:
    password: ${encoding_password}